#!/bin/sh
echo "------------------------------------------------------------"
echo "Reset yadm to HEAD"
yadm reset HEAD --hard
echo "Decrypting files"
yadm decrypt # (enter password)
echo "Starting ssh-agent and adding SSH key"
eval $(ssh-agent -s)
if [[ "$OSTYPE" == "linux-gnu"* ]]; then
    ssh-add ~/.ssh/github_id_ed25519
elif [[ "$OSTYPE" == "darwin"* ]]; then
    # Mac OSX
    ssh-add --apple-use-keychain  ~/.ssh/github_id_ed25519
else
    : # Do nothing
    echo "Unknown Operating system: $OSTYPE"
    exit
fi
echo "Testing ssh connection to github.com"
ssh -T git@github.com
echo "Updating the yadm repo origin URL"
yadm remote set-url origin "git@github.com:iancleary/dotfiles.git"
echo "------------------------------------------------------------"
