#!/bin/sh
echo "------------------------------------------------------------"
echo "Reset yadm to HEAD"
yadm reset HEAD --hard
echo "Decrypting files"
yadm decrypt # (enter password)
echo "Starting ssh-agent and adding SSH key"
eval $(ssh-agent -s)
ssh-add ~/.ssh/github_id_ed25519
echo "Testing ssh connection to github.com"
ssh -T git@github.com
echo "Updating the yadm repo origin URL"
yadm remote set-url origin "git@github.com:icancclearynow/dotfiles.git"
echo "------------------------------------------------------------"
